version: '3'

services:
  api:
    container_name: fieldsensing-api
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
            - ./:/go/src/github.com/Pluslab/gaia:Z
    ports:
      - 8080:8080
    tty:
      true
  react:
    container_name: fieldsensing-react
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    volumes:
            - ./frontend:/frontend:Z
    ports:
      - 8081:8081
    tty:
      true
  db:
    image: mysql:latest
    container_name: fieldsensing-mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/access.cnf:/home/access.cnf
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
